In [2]:
import pandas as pd

# reading the dataset using pandas csv reader
df = pd.read_csv("air_quality_health_dataset.csv")
display(df)

,city,date,aqi,pm2_5,pm10,no2,o3,temperature,humidity,hospital_admissions,population_density,hospital_capacity
0,Los Angeles,2020-01-01,65,34.0,52.7,2.2,38.5,33.5,33,5,Rural,1337
1,Beijing,2020-01-02,137,33.7,31.5,36.7,27.5,-1.6,32,4,Urban,1545
2,London,2020-01-03,266,43.0,59.6,30.4,57.3,36.4,25,10,Suburban,1539
3,Mexico City,2020-01-04,293,33.7,37.9,12.3,42.7,-1.0,67,10,Urban,552
4,Delhi,2020-01-05,493,50.3,34.8,31.2,35.6,33.5,72,9,Suburban,1631
...,...,...,...,...,...,...,...,...,...,...,...,...
88484,Tokyo,2262-04-06,22,23.4,53.4,24.3,58.9,9.1,55,5,Suburban,419
88485,Delhi,2262-04-07,170,48.0,32.4,25.0,15.7,5.6,40,10,Urban,695
88486,Delhi,2262-04-08,307,46.7,21.8,31.9,45.1,9.5,44,12,Urban,245
88487,Beijing,2262-04-09,65,31.9,26.0,38.1,53.0,17.8,46,11,Suburban,1291
88488,Mexico City,2262-04-10,59,41.8,50.1,31.2,52.0,25.0,65,8,Urban,983

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# reading the dataset as a dataframe using pandas using try-except block
try: 
    df = pd.read_csv("air_quality_preprocessed_dataset.csv", encoding="utf-8-sig")

except IOError as err:
    print("Unable to open pre-processed file 'air_quality_preprocessed_dataset.csv' : {}".format(err), file=sys.stderr)
    sys.exit(1)

# using plotly to create a bar graph
plotly_fig = px.bar(df, x="City", y="AQI", title="Air Quality Metrics in Cities")
plotly_fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Los Angeles', '65'] but received: City